
/**
 * This code was generated by [react-native-codegen](https://www.npmjs.com/package/react-native-codegen).
 *
 * Do not edit this file as changes may cause incorrect behavior and will be lost
 * once the code is regenerated.
 *
 * @generated by codegen project: GeneratePropsH.js
 */
#pragma once

#include <react/renderer/components/view/ViewProps.h>
#include <react/renderer/core/PropsParserContext.h>

namespace facebook {
namespace react {

class ClipPathProps final : public ViewProps {
 public:
  ClipPathProps() = default;
  ClipPathProps(const PropsParserContext &context, const ClipPathProps &sourceProps, const RawProps &rawProps);

#pragma mark - Props
  std::string color{"#00f"};
  bool openClip{true};
  std::string fill{};

  std::string svgKey{};
  std::string d{};
  std::vector<int> viewBox{};
  //     std::array<int, 4> viewBox{};
  std::string align{};
  std::string aspect{};
  std::string fillRule{};
  int strokeWidth{};
  std::string strokeCap{};
  std::string strokeJoin{};
  int strokeMiter{};
  int strokeStart{};
  int strokeEnd{};

  int translateZ{};
  int transX{};
  int transY{};
  bool transPercentageValue{false};
  int rot{};
  int rotOx{};
  int rotOy{};
  bool rotPercentageValue{false};
  int sc{};
  int scX{};
  int scY{};
  int scO{};
  int scOx{};
  int scOy{};
  bool scPercentageValue{false};
};

} // namespace react
} // namespace facebook
